index:
   path: /
   controller: App\Controller\HomeController::index

applications_list:
   path: applications
   controller: App\Controller\ApplicationController::list

applications_create:
   path: applications/create
   controller: App\Controller\ApplicationController::create

applications_transit:
   path: applications/{id}/{transition}
   controller: App\Controller\ApplicationController::transit
   requirements:
      transition: forward|backward
   methods: put
